การสร้าง numpy arrary

In [1]:
import numpy as np

สร้างจาก list

In [2]:
my_list1 = [1,2,3,4,5]
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4, 5])

In [3]:
my_array1.shape

(5,)

In [4]:
my_list2 = [11,22,33,44,55]
my_lists = [my_list1, my_list2]
my_lists

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [5]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [6]:
my_array2.shape

(2, 5)

In [7]:
my_array2.dtype

dtype('int64')

สร้าง array ที่มีสมาชิกเป็น 0 จำนวน 5 ตัว

In [8]:
my_zeros_array = np.zeros(5) # สามารถใช้ np.empty(5) แทนได้
my_zeros_array

array([0., 0., 0., 0., 0.])

In [9]:
my_zeros_array.dtype

dtype('float64')

สร้าง array ที่มีสมาชิกเป็น 1 จำนวน 5x5

In [10]:
my_ones_array = np.ones([5,5])
my_ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
my_ones_array.dtype

dtype('float64')

สร้าง identity matrix

In [12]:
my_iden_array = np.eye(5)
my_iden_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

สร้างจาก method arange

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])